# Site settings
title: PowerShell Escape
description: 'a blog about Powershell, DevOps, and all things Microsoft and IT'
url: 'http://mattmcnabb.github.io'
#url: 'http://localhost:4000' 
baseurl: '/'
google_analytics: 'UA-69802890-1'
disqus_shortname: mattmcnabbgithubio

author:
  name: 'Matt McNabb'
  email: mmcnabb@outlook.com
  twitter_username: mcnabbmh
  github_username:  mattmcnabb
  #linkedin_username:  

# Build settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems:
  - jekyll-sitemap

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
